apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-platform-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: northamerica-northeast1-docker.pkg.dev/gcp-class-14/banking-repo/banking
          ports:
            - containerPort: 8080
          # HARDCODED FOR TESTING ONLY 
          env:
          - name: JWT_SECRET
            value: "ThisIsADevOnlySecretKeyForHs256JwtTokenMinimum32Chars"
 