steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=JWT_SECRET=ThisIsADevOnlySecretKeyForHs256JwtTokenMinimum32Chars

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: northamerica-northeast1-docker.pkg.dev/gcp-class-14/banking-repo/banking
  _SERVICE: digital-banking-service
  _REGION: northamerica-northeast1