steps:
  # Step 1: Build + Test + Sonar
  - name: 'maven:3.9.9-eclipse-temurin-21'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=shinyshuckle168_banking-platform \
          -Dsonar.organization=fdm-gcp-2026 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', '${_IMAGE}', '.']

  # Step 3: Trivy Scan (CRITICAL ONLY)
  - name: 'aquasec/trivy:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy image \
          --severity CRITICAL \
          --ignore-unfixed \
          --exit-code 1 \
          ${_IMAGE}

  # Step 4: Push Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=JWT_SECRET=ThisIsADevOnlySecretKeyForHs256JwtTokenMinimum32Chars

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
      env: 'SONAR_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: northamerica-northeast1-docker.pkg.dev/gcp-class-14/banking-repo/banking
  _SERVICE: digital-banking-service
  _REGION: northamerica-northeast1