steps:
  - name: 'maven:3.9.9-eclipse-temurin-21'
    dir: 'backend'
    entrypoint: 'bash'
    secretEnv: ['SONAR_TOKEN']
    args:
      - '-c'
      - |
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=shinyshuckle168_banking-platform \
          -Dsonar.organization=fdm-gcp-2026 \
          -Dsonar.host.url=https://sonarcloud.io

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', '${_IMAGE}:$SHORT_SHA', '.']

  - name: 'aquasec/trivy:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy image \
          --severity CRITICAL \
          --ignore-unfixed \
          --exit-code 1 \
          ${_IMAGE}:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=backend/k8s/ # The directory where your Kubernetes manifests are
      - --image=${_IMAGE}:$SHORT_SHA
      - --location=${_GKE_REGION}
      - --cluster=${_CLUSTER}
      - --namespace=dev-banking-backend

availableSecrets:
  secretManager:
    - versionName: projects/gcp-class-14/secrets/sonar-cloud-auth-token/versions/latest
      env: 'SONAR_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: northamerica-northeast1-docker.pkg.dev/gcp-class-14/banking-repo/banking
  _SERVICE: digital-banking-service
  _REGION: northamerica-northeast1
  _GKE_REGION: us-central1
  _CLUSTER: my-gke-cluster