apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: banking-platform
  description: Banking Platform
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: shinyshuckle168/banking-platform
  tags:
    - banking-platform
    - fdm
  links:
    - url: https://github.com/shinyshuckle168/banking-platform
      title: Github Repo
      icon: source
      type: source-code
    - url: https://console.cloud.google.com/cloud-build/dashboard?authuser=4&project=gcp-class-14
      title: Google Cloud Build
      icon: dashboard
      type: ci-cd
spec:
  type: service
  lifecycle: development
  owner: admin