apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-platform-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: northamerica-northeast2-docker.pkg.dev/gcp-class-14/quickstart-docker-repo/frontend
          ports:
            - containerPort: 8080
 