spring.application.name=digital-banking-platform-backend
server.port=8080
 
#spring.datasource.url=jdbc:h2:mem:digitalbankdb
spring.datasource.url=jdbc:h2:file:./data/digitalbankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
 
jwt.secret=${JWT_SECRET:ThisIsADevOnlySecretKeyForHs256JwtTokenMinimum32Chars}
jwt.access-token-expiry=3600
jwt.refresh-token-expiry=604800
 
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
 
# Logging
logging.file.name=logs/digital-banking.log
logging.level.root=INFO
logging.level.com.group1.banking=INFO
logging.level.org.springframework.security=INFO